<?php
use Slim\Views\PhpRenderer;
use Slim\Interfaces\RouteParserInterface;
use Blog\Markdown;
use Blog\Formatter\DateFormatterInterface;
use Blog\Model\PostInterface;

/**
 * @var PhpRenderer $this
 * @var RouteParserInterface $routeParser
 * @var Markdown\ParserInterface $markdown
 * @var DateFormatterInterface $dateFormatter
 * @var PostInterface $post
 */

$id = $post->getId();
//var_dump($post);
?>
<h1><?= $id > 0 ? "Редактирование записи #{$id}" : 'Добавление записи' ?></h1>
<form method="post" action="?id=<?= $id ?>">
    <?php if ($id > 0): ?>
        <p>
            ID: <?= $post->getId() ?><br>
            Создан: <?= $post->getCreatedAt() ?>
        </p>
    <?php endif; ?>
    <p>
        <label>slug:</label>
        <input name="slug" type="text" value="<?= htmlspecialchars($post->getSlug()) ?>">
    </p>
    <p>
        <label>Заголовок:</label>
        <input name="name" type="text" value="<?= htmlspecialchars($post->getName()) ?>" required>
    </p>
    <p>
        <label>Preview:</label>
        <textarea name="preview"><?= htmlspecialchars($post->getPreview()) ?></textarea>
    </p>
    <p>
        <label>Текст:</label>
        <textarea name="text" required><?= htmlspecialchars($post->getText()) ?></textarea>
    </p>
    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>
