<?php
use Slim\Views\PhpRenderer;
use Slim\Interfaces\RouteParserInterface;
use Blog\Markdown;
use Blog\Formatter\DateFormatterInterface;
use Blog\Model\PostInterface;
use Blog\Model\TagInterface;

/**
 * @var PhpRenderer $this
 * @var RouteParserInterface $routeParser
 * @var Markdown\ParserInterface $markdown
 * @var DateFormatterInterface $dateFormatter
 * @var PostInterface $post
 * @var TagInterface[] $tags
 */

$postId = $post->getId();
?>
<h1><?= $postId > 0 ? "Редактирование записи #{$postId}" : 'Добавление записи' ?></h1>
<form method="post" action="?id=<?= $postId ?>">
    <?php if ($postId > 0): ?>
        <p>
            ID: <?= $post->getId() ?><br>
            Создан: <?= $post->getCreatedAt() ?>
        </p>
    <?php endif; ?>
    <p>
        <label>slug:</label>
        <input name="slug" type="text" value="<?= htmlspecialchars($post->getSlug()) ?>">
    </p>
    <p>
        <label>Заголовок:</label>
        <input name="name" type="text" value="<?= htmlspecialchars($post->getName()) ?>" required>
    </p>
    <p>
        <label>Preview:</label>
        <textarea name="preview"><?= htmlspecialchars($post->getPreview()) ?></textarea>
    </p>
    <p>
        <label>Текст:</label>
        <textarea name="text" required><?= htmlspecialchars($post->getText()) ?></textarea>
    </p>
    <p>
        <label>Теги:</label>
        <select name="tags[]" size="5" multiple>
            <option>Выберите тег</option>
            <?php
            $postTags = $post->getTags();

            foreach ($tags as $tagId => $tag)
            {
                $selected = isset($postTags[$tagId]) ? 'selected' : null;
                ?>
                <option value="<?= $tagId ?>" <?= $selected ?>><?= htmlspecialchars($tag->getName()) ?> [<?= $tagId ?>]</option>
                <?php
            }
            ?>
        </select>
    </p>
    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>
