<?php
use Slim\Views\PhpRenderer;
use Slim\Interfaces\RouteParserInterface;
use Blog\Markdown;
use Blog\Formatter\DateFormatterInterface;
use Blog\Model\PostInterface;
use Blog\Model\TagInterface;

/**
 * @var PhpRenderer $this
 * @var RouteParserInterface $routeParser
 * @var Markdown\ParserInterface $markdown
 * @var DateFormatterInterface $dateFormatter
 * @var PostInterface $post
 * @var TagInterface[] $tags
 */

$postId = $post->getId();
?>
<h1><?= $postId > 0 ? "Редактирование записи #{$postId}" : 'Добавление записи' ?></h1>
<form class="form" method="post" action="?id=<?= $postId ?>">
    <?php if ($postId > 0): ?>
        <div class="form__row">
            ID: <?= $post->getId() ?><br>
            Дата создания: <?= $post->getCreatedAt()->format('Y-m-d h:i:s') ?>
        </div>
    <?php endif; ?>
    <div class="form__row">
        <label class="form__label">Код: <span class="req">*</span></label>
        <input name="slug" type="text" value="<?= htmlspecialchars($post->getSlug()) ?>" required>
    </div>
    <div class="form__row">
        <label class="form__label">Заголовок: <span class="req">*</span></label>
        <input name="name" type="text" value="<?= htmlspecialchars($post->getName()) ?>" required>
    </div>
    <div class="form__row">
        <label class="form__label">Превью текст:</label>
        <textarea name="preview"><?= htmlspecialchars($post->getPreview()) ?></textarea>
    </div>
    <div class="form__row">
        <label class="form__label">Текст: <span class="req">*</span></label>
        <textarea name="text" required><?= htmlspecialchars($post->getText()) ?></textarea>
    </div>
    <div class="form__row">
        <label class="form__label">Теги:</label>
        <select name="tags[]" size="5" multiple>
            <option>Выберите тег:</option>
            <?php
            foreach ($tags as $tag)
            {
                $tagId = $tag->getId();
                $selected = $post->getTags()->contains($tag) ? 'selected' : null;
                ?>
                <option value="<?= $tagId ?>" <?= $selected ?>><?= htmlspecialchars($tag->getName()) ?> [<?= $tagId ?>]</option>
                <?php
            }
            ?>
        </select>
    </div>
    <div class="form__row form__footer">
        <button class="btn btn--primary" type="submit">Сохранить</button>
    </div>
</form>
