<?php
use Blog\Formatter\DateFormatterInterface;
use Blog\Markdown;
use Blog\Model\PostInterface;
use Blog\Nav\QueryPaginator;
use Slim\Interfaces\RouteParserInterface;
use Slim\Views\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var RouteParserInterface $routeParser
 * @var Markdown\ParserInterface $markdown
 * @var DateFormatterInterface $dateFormatter
 * @var PostInterface[] $posts
 * @var QueryPaginator $paginator
 * @var string $paginationRoute
 * @var array $paginationData
 */

foreach ($posts as $post)
{
    $postUrl = $routeParser->urlFor('post', [
        'slug' => $post->getSlug(),
    ]);

    ?>
    <div class="post">
        <div class="post__date"><?= $dateFormatter->format($post->getCreatedAt()) ?></div>
        <h2 class="post__title"><a href="<?= $postUrl ?>">
            <?= htmlspecialchars($post->getName()) ?></a>
        </h2>
        <?php
        $tags = $post->getTags();
        require __DIR__ . '/parts/post.tags.phtml';

        $preview = $post->getPreview();

        if (!empty($preview))
        {
            ?>
            <div class="post__content">
                <?= $markdown->parse($preview) ?>
            </div>
            <?php
        }
        ?>
    </div>
    <?php
}

require __DIR__ . '/parts/pagination.phtml';
