<?php
use Blog\Nav\QueryPaginator;
use Slim\Interfaces\RouteParserInterface;

/**
 * @var RouteParserInterface $routeParser
 * @var QueryPaginator $paginator
 */

$totalPages = $paginator->getTotalPages();

if ($totalPages > 1)
{
    echo '<div class="pagination">Страницы: ';

    $page = $paginator->getPage();

    for ($i = 1; $i <= $totalPages; $i++)
    {
        $paginationTag = $paginationTagOpen = $i === $page ? 'span' : 'a';

        if ($paginationTagOpen === 'a')
        {
            $paginationTagOpen .= sprintf(' href="%s"', $paginator->getUrl($routeParser, $i));
        }

        echo '<' . $paginationTagOpen . '>' . $i . '</' . $paginationTag . '>';
    }

    echo '</div>';
}
