<?php
use Slim\Views\PhpRenderer;
use Slim\Interfaces\RouteParserInterface;
use Blog\Markdown;
use Blog\Utils\DateFormatter;
use Blog\Model\PostInterface;

/**
 * @var PhpRenderer $this
 * @var RouteParserInterface $routeParser
 * @var PostInterface $post
 * @var Markdown\ParserInterface $markdown
 * @var DateFormatter $dateFormatter
 */
?>
<div class="post">
    <div class="post__date"><?= $dateFormatter->format($post->getCreatedAt()) ?></div>
    <h1 class="post__title"><?= htmlspecialchars($post->getName()) ?></h1>
    <?php
    $tags = $post->getTags();
    require __DIR__ . '/parts/post.tags.phtml';
    ?>
    <div class="post__content post__content--full">
        <?= $markdown->parse(htmlspecialchars($post->getFullText())) ?>
    </div>
</div>
