<?php
use Slim\Views\PhpRenderer;
use Slim\Interfaces\RouteParserInterface;
use Blog\Markdown;
use Blog\Formatter\DateFormatterInterface;
use Blog\Model\PostInterface;
use Blog\Model\TagInterface;

/**
 * @var PhpRenderer $this
 * @var RouteParserInterface $routeParser
 * @var Markdown\ParserInterface $markdown
 * @var DateFormatterInterface $dateFormatter
 * @var TagInterface $tag
 * @var PostInterface[] $posts
 * @var int $page
 * @var int $totalPages
 * @var string $paginationRoute
 * @var array $paginationData
 */

require __DIR__ . '/index.phtml';
