<?php
use Blog\Markdown;
use Blog\Model\PostInterface;
use Blog\Model\TagInterface;
use Blog\Nav\QueryPaginator;
use Slim\Interfaces\RouteParserInterface;
use Slim\Views\PhpRenderer;

/**
 * @var PhpRenderer $this
 * @var RouteParserInterface $routeParser
 * @var Markdown\ParserInterface $markdown
 * @var TagInterface $tag
 * @var PostInterface[] $posts
 * @var QueryPaginator $paginator
 * @var string $paginationRoute
 * @var array $paginationData
 */

require __DIR__ . '/index.phtml';
