<?php
use Blog\Nav\QueryPaginator;
use Slim\Interfaces\RouteParserInterface;

/**
 * @var RouteParserInterface $routeParser
 * @var QueryPaginator $paginator
 * @var string $paginationRoute
 * @var array $paginationData
 */

$totalPages = $paginator->getTotalPages();

if ($totalPages > 1)
{
    echo '<div class="pagination">Страницы: ';

    $page = $paginator->getPage();

    for ($i = 1; $i <= $totalPages; $i++)
    {
        $paginationTag = $paginationTagOpen = $i === $page ? 'span' : 'a';

        if ($paginationTagOpen === 'a')
        {
            if ($i > 1)
                $paginationData['page'] = $i;

            $paginationTagOpen .= sprintf(' href="%s"', $routeParser->urlFor($paginationRoute, $paginationData));
        }

        echo '<' . $paginationTagOpen . '>' . $i . '</' . $paginationTag . '>';
    }

    echo '</div>';
}
