<?php
use Slim\Interfaces\RouteParserInterface;
use Blog\Model\TagInterface;

/**
 * @var RouteParserInterface $routeParser
 * @var TagInterface[] $tags
 */

if (!count($tags))
    return;

?>
<div class="post__meta">
    🏷️
    <?php
    $htmlTags = [];

    foreach ($tags as $tag)
    {
        $itemUrl = $routeParser->urlFor('tag', [
            'name' => $tag->getName(),
        ]);

        $htmlTags[] = sprintf('<a href="%s">%s</a>', $itemUrl, htmlspecialchars($tag->getTitle() ?? $tag->getName()));
    }

    echo implode(', ', $htmlTags);
    ?>
</div>
